### ISSUE TITLE
unable to enable extension

### ISSUE THREAD

**Issue by Nory-01** [datlechin/flarum-birthdays#22]
hello,
 it's impossible to activate the extention in back office. 
I have install, and uninstall the extention, and the isse is the same.
the extention version is v2.1.1

**Comment by datlechin** [comment]
Can I get the error when you trying to activate the extension and `php flarum info` output?

**Comment by Nory-01** [comment]
I don't have error message when i triy to activate the extention.

php flarum info output
Flarum core: 1.8.3
PHP version: 8.1.28
MySQL version: 5.7.42-log
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, FFI, fileinfo, filter, ftp, gd, gettext, gmp, json, iconv, SPL, session, intl, standard, mbstring, memcached, mongodb, mysqlnd, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, Reflection, imagick, SimpleXML, soap, sockets, sodium, imap, ssh2, exif, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, mysqli, ionCube Loader, Zend OPcache
+----------------------------------+---------------+--------+
| Flarum Extensions                |               |        |
+----------------------------------+---------------+--------+
| ID                               | Version       | Commit |
+----------------------------------+---------------+--------+
| fof-pages                        | 1.0.8         |        |
| flarum-tags                      | v1.8.0        |        |
| flarum-markdown                  | v1.8.0        |        |
| flarum-flags                     | v1.8.0        |        |
| flarum-suspend                   | v1.8.1        |        |
| fof-sitemap                      | 2.2.1         |        |
| v17development-seo               | v1.8.0        |        |
| askvortsov-rich-text             | v2.1.7        |        |
| flarum-sticky                    | v1.8.0        |        |
| flarum-lock                      | v1.8.0        |        |
| afrux-forum-widgets-core         | v0.1.7        |        |
| fof-spamblock                    | 1.1.2         |        |
| blomstra-gdpr                    | 0.1.0-beta.20 |        |
| flarum-approval                  | v1.8.0        |        |
| webbinaro-calendar               | 1.7.0         |        |
| v17development-blog              | v0.7.7        |        |
| the-turk-stickiest               | 3.0.1         |        |
| nearata-prevent-double-posting   | 1.1.0         |        |
| nearata-cakeday                  | v2.2.0        |        |
| michaelbelgium-discussion-views  | v7.2.1        |        |
| littlecxm-whisper                | 0.1.5         |        |
| justoverclock-welcomebox         | 2.0.2         |        |
| justoverclock-hot-discussions    | 0.1.2         |        |
| jslirola-login2seeplus           | v0.2.1        |        |
| ianm-log-viewer                  | 0.1.1         |        |
| fof-user-bio                     | 1.3.1         |        |
| fof-upload                       | 1.4.6         |        |
| fof-terms                        | 1.3.0         |        |
| fof-stopforumspam                | 1.2.4         |        |
| fof-split                        | 1.1.1         |        |
| fof-socialprofile                | 1.1.6         |        |
| fof-pretty-mail                  | 1.1.2         |        |
| fof-oauth                        | 1.6.2         |        |
| fof-nightmode                    | 1.5.3         |        |
| fof-merge-discussions            | 1.4.1         |        |
| fof-links                        | 1.2.3         |        |
| fof-frontpage                    | 1.2.0         |        |
| fof-default-group                | 1.1.2         |        |
| fof-cookie-consent               | 1.1.3         |        |
| fof-clockwork                    | 1.0.4         |        |
| fof-best-answer                  | 1.4.2         |        |
| fof-ban-ips                      | 1.1.1         |        |
| fof-analytics                    | 1.1.0         |        |
| flarum-subscriptions             | v1.8.0        |        |
| flarum-statistics                | v1.8.0        |        |
| flarum-nicknames                 | v1.8.0        |        |
| flarum-mentions                  | v1.8.2        |        |
| flarum-likes                     | v1.8.0        |        |
| flarum-lang-french               | v4.17.0       |        |
| flarum-extension-manager         | v1.0.1        |        |
| flarum-bbcode                    | v1.8.0        |        |
| davwheat-custom-sidenav-links    | 1.0.1         |        |
| datlechin-simple-tour-guide      | v0.0.1        |        |
| datlechin-link-preview           | v1.4.0        |        |
| clarkwinkelmann-mass-actions     | 1.1.2         |        |
| clarkwinkelmann-mailing          | 1.1.0         |        |
| clarkwinkelmann-formatted-banner | 1.0.0         |        |
| clarkwinkelmann-emojionearea     | 1.0.0         |        |
| clarkwinkelmann-circle-groups    | 1.0.1         |        |
| askvortsov-pwa                   | v3.3.3        |        |
| askvortsov-markdown-tables       | v1.2.1        |        |
| askvortsov-categories            | v3.0.9        |        |
| afrux-top-posters-widget         | v0.1.4        |        |
| afrux-online-users-widget        | v0.1.6        |        |
| afrux-news-widget                | v0.1.1        |        |
+----------------------------------+---------------+--------+
